spring:
    profiles:
        active: testbed
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    thymeleaf:
        cache: true
server:
    port: 8081
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
zuul:
  routes:
    voldemort:
      path: /api/**
      url: http://testbed.avand.io:8080/api
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000